apiVersion: v1
kind: Secret
metadata:
  name: csi-fs-secret 
  namespace: kube-system
stringData:
  userID: kubernetes # Esse usuário foi criado no ceph, você pode deixar só o usuario admin
  userKey: "Sua chave de acesso" # Obtenha com ceph auth list
  adminID: admin
  adminKey: "Sua chave de acesso" # Obtenha com ceph auth list
